### ISSUE TITLE
ESP32 Fails to Connect to Azure cloud

### ISSUE THREAD

**Issue by amardhore** [Azure-Samples/iot-hub-c-esp32#1]
This is my first post on Github. Excuse me if I am not following any syntax.

I have a setup ESP32 -wroom dev  board. Azure IoT cloud, up and running.

I followed the steps as described in this post. I am able to connect to the azure IoT hub. 
I made sure if my IoT hub is running with this (https://github.com/Azure/iothub-diagnostics ).  
The program fails at SSL_connect. I get the error message. ( socket return this error no. lwip_net_errno ret: 119)
I can successfully connect to the WiFi. I tried updating mbed tls certificate but no luck. 
Any help would be appreciated. Thank you.

Below are my logs from the monitor window:

Info: lwip_net_errno ret: 119
SSL connect...
SSL_connect succeedError: Time:Wed Jul 12 02:55:08 2017 File:C:/esp/myapp/components/azure_iot/azure/umqtt/src/mqtt_client.c Func:sendComplete Line:182 MQTT Send Complete Failure send_result:1
Error: Time:Wed Jul 12 02:55:08 2017 File:C:/esp/myapp/components/azure_iot/azure/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1441 INTERNAL ERROR: unexpected
error value received MQTT_CLIENT_COMMUNICATION_ERROR
Error: Time:Wed Jul 12 02:55:08 2017 File:C:/esp/myapp/components/azure_iot/adapter/azure/c-utility/tlsio_ssl_esp32.c Func:tlsio_openssl_dowork Line:727 Invalid tlsio_state for dowork. Expecte
d state is TLSIO_STATE_OPEN.
Error: Time:Wed Jul 12 02:55:08 2017 File:C:/esp/myapp/components/azure_iot/azure/umqtt/src/mqtt_client.c Func:sendPacketItem Line:323 690: Failure sending control packet data
Error: Time:Wed Jul 12 02:55:08 2017 File:C:/esp/myapp/components/azure_iot/azure/umqtt/src/mqtt_client.c Func:onOpenComplete Line:358 Error: mqtt_codec_connect failed

--
Amar Dhore

[esp32_logs.txt](https://github.com/Azure-Samples/iot-hub-c-esp32/files/1165968/esp32_logs.txt)

**Comment by JetstreamRoySprowl** [comment]
The file tlsio_esp32.c is not one of the Azure IoT SDK files, but it sounds like you've modified it from tlsio_mbedtls.c. Is that correct?

**Comment by stevebus** [comment]
since Amar is only occasionally on, I'll answer for him...  the tlsio_ssl_esp32.c file came from the Espressif "getting started" sample here ->  https://github.com/ustccw/AzureESP32/blob/master/components/azure_iot/adapter/azure/c-utility/tlsio_ssl_esp32.c    This is the same GitHub repro referenced in the readme here.   That's one of the files you have to port that is HW specific in the porting guide which, we assume, either Espressif or MSFT provided.

**Comment by JetstreamRoySprowl** [comment]
I see. That Espressif sample is based on a much older version of the Azure IoT SDK. There is an ESP32 sample that is based on the latest and greatest Azure IoT SDK [here](https://github.com/Azure-Samples/iot-hub-c-esp32), which I strongly recommend going to.

**Comment by amardhore** [comment]
Roy, Let me try with the latest IoT SDK and I will update you guys here.
Thank you for the responses.

**Comment by amardhore** [comment]
Roy, Azure cloud seems to be working. I had fake a "iothub_client_sample_mqtt.h" file as the compiler was complaining. 
Question: messages I received on the cloud has dates a month old. Shouldn't it be the latest time and date?
Any comments on the log file??

Thank you for the help.

[AzureIot_log.txt](https://github.com/Azure-Samples/iot-hub-c-esp32/files/1168112/AzureIot_log.txt)

**Comment by JetstreamRoySprowl** [comment]
@amardhore The log file looks normal as far as I see. I don't know what might be up with the log file dates offhand. Some of the IoT Hub samples create simulated devices which start reporting immediately, so perhaps its one of those? Is there anything else you need for this?
