### ISSUE TITLE
Compile errors for sample ESP32 + ESP-IDF

### ISSUE THREAD

**Issue by sukeshak** [Azure-Samples/iot-hub-c-esp32#2]
Is this the branch for latest Azure IoT Hub samples for ESP32? If not please point to the right place.

I went through the steps as described but unable to compile the sample. Errors below
https://github.com/Azure-Samples/iot-hub-c-esp32/blob/master/README.md

`LD build/esp32.elf
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o):(.literal.InitializeTransportHandleData+0x3c): undefined reference to `retry_control_create'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o):(.literal.InitializeTransportHandleData+0x40): undefined reference to `retry_control_destroy'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o):(.literal.mqtt_operation_complete_callback+0x1c): undefined reference to `retry_control_reset'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o):(.literal.InitializeConnection+0x14): undefined reference to `retry_control_should_retry'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o): In function `InitializeTransportHandleData':
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_create'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_destroy'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_destroy'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_destroy'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_destroy'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_destroy'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o):D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: more undefined references to `retry_control_destroy' follow
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o): In function `mqtt_operation_complete_callback':
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_reset'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o): In function `InitializeConnection':
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:88: undefined reference to `retry_control_should_retry'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o): In function `IoTHubTransport_MQTT_Common_SetRetryPolicy':
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:280: undefined reference to `retry_control_create'
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:290: undefined reference to `retry_control_destroy'
D:/msys32/home/sukesh/esp/AzureIoTClient_sample_mqtt/build/azure-iot\libazure-iot.a(iothubtransport_mqtt_common.o): In function `IoTHubTransport_MQTT_Common_Destroy':
D:/github/esp/esp-idf/components/azure-iot/sdk/iothub_client/src/iothubtransport_mqtt_common.c:1970: undefined reference to `retry_control_destroy'
collect2.exe: error: ld returned 1 exit status
make: *** [d:/github/esp/esp-idf/make/project.mk:330: /home/sukesh/esp/AzureIoTClient_sample_mqtt/build/esp32.elf] Error 1
`

**Comment by JetstreamRoySprowl** [comment]
@sukeshak : we had some trouble getting our SDK submodules in sync, but that should be resolved later today. The problem it caused is that the component.mk file in the top-level SDK is not in sync with the latest in the C Shared Utilities submodule. If you replace your component.mk file that sits next to the Azure IoT SDK with [this one](https://github.com/Azure/azure-c-shared-utility/blob/master/build_all/esp32/sdk/component.mk), that will pull in the missing file and you should be okay then.

**Comment by sukeshak** [comment]
Thank you. Will try the suggestion and revert.

**Comment by sukeshak** [comment]
Thank you. Yes its compiling now. Once uploaded its stuck at connecting to Wi-Fi. I checked and cross verified for the Wi-Fi to be working and password is also correct. Any ideas?
(Hacked is my router)

I (0) cpu_start: App cpu up.
I (1152) heap_init: Initializing. RAM available for dynamic allocation:
I (1173) heap_init: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM
I (1192) heap_init: At 3FFB8B78 len 00027488 (157 KiB): DRAM
I (1211) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (1231) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1251) heap_init: At 4009379C len 0000C864 (50 KiB): IRAM
I (1270) cpu_start: Pro cpu start user code
I (1329) cpu_start: Starting scheduler on PRO CPU.
I (193) cpu_start: Starting scheduler on APP CPU.
I (253) wifi: wifi firmware version: c1b8a2f
I (253) wifi: config NVS flash: enabled
I (253) wifi: config nano formating: disabled
I (253) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (263) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (293) wifi: Init dynamic tx buffer num: 32
I (293) wifi: Init data frame dynamic rx buffer num: 32
I (293) wifi: Init management frame dynamic rx buffer num: 32
I (293) wifi: wifi driver task: 3ffbf0e4, prio:23, stack:4096
I (303) wifi: Init static rx buffer num: 10
I (303) wifi: Init dynamic rx buffer num: 32
I (303) wifi: Init rx ampdu len mblock:7
I (313) wifi: Init lldesc rx ampdu entry mblock:4
I (313) wifi: wifi power manager task: 0x3ffc4448 prio: 21 stack: 2560
I (323) azure: Setting WiFi configuration SSID hacked...
I (333) wifi: wifi timer task: 3ffc54b4, prio:22, stack:3584
I (363) phy: phy_version: 357.0, a6bf95b, Jul 25 2017, 12:28:06, 0, 0
I (363) wifi: Init Ampdu: 1 tx baw=6 rx baw=6
I (363) wifi: mode : sta (30:ae:a4:09:10:94)
I (363) azure: Waiting for WiFi access point ...

**Comment by JetstreamRoySprowl** [comment]
No clue from here, I'm afraid: I've only seen that failure when either password or SSID is wrong (I believe it's also case-sensitive). It's all in the Espressif code from there.

**Comment by sukeshak** [comment]
ok now it worked. This helped => (I believe it's also case-sensitive)
Never thought the SSID is case sensitive. Thank you so much 👍

**Comment by sukeshak** [comment]
Please check if you can include Azure-iot as a standard component like what is done for aws_iot, so that these additional steps are not required to get it installed.

**Comment by JetstreamRoySprowl** [comment]
Glad you got it working! I'll pass your suggestion up to my boss.
